create table wallets (
        uuid uuid not null,
        count bigint not null,
           primary key (uuid)
    );

create table transaction (
        id bigint generated by default as identity,
        amount bigint not null,
        operation_type varchar(255) not null check (operation_type in ('DEPOSIT','WITHDRAW')),
        wallet_uuid uuid,
        primary key (id)
    );

    insert into wallets ("count","uuid")
	values (0,'33fa31a5-87d6-4906-b252-4e8e43df0064');
